In [206]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from PIL import Image
import pickle 

In [180]:
df = pd.read_csv('data.csv')

In [181]:
def Add_Image(path):
    df = pd.read_csv('data.csv')
    img=Image.open(path)
    new_img=img.resize((64,64),Image.ANTIALIAS)
    new_img.save('image_test.jpg')
    k=cv2.imread(f'image_test.jpg')
    k=k.reshape(-1,12288)
    print(k)
    
    return k

In [182]:
img_1=Image.open('img_1.jpg')

In [183]:
s=np.asarray(img_1)
s=s.reshape(-1,12288)

In [184]:
img_2=Image.open('img_2.jpg')
o=np.asarray(img_2).reshape(-1,12288)

In [185]:
img_3=Image.open('img_3.jpg')
n=np.asarray(img_3).reshape(-1,12288)

In [207]:
p=[s[0],o[0],n[0]]

In [187]:
p

[array([230, 228, 229, ..., 208, 206, 207], dtype=uint8),
 array([247, 247, 247, ..., 247, 245, 255], dtype=uint8),
 array([189, 189, 191, ..., 177, 174, 181], dtype=uint8)]

In [188]:
k=Add_Image('img_4.jpg')

[[255 255 255 ... 255 255 255]]


In [189]:
p.append(k[0])

In [190]:
p

[array([230, 228, 229, ..., 208, 206, 207], dtype=uint8),
 array([247, 247, 247, ..., 247, 245, 255], dtype=uint8),
 array([189, 189, 191, ..., 177, 174, 181], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8)]

In [191]:
df=pd.DataFrame(p)

In [192]:
df

0      1      2      3      4      5      6      7      8      9      ...  \
0    230    228    229    230    228    229    229    227    230    229  ...   
1    247    247    247    247    247    247    247    247    247    247  ...   
2    189    189    191    189    189    191    189    189    191    189  ...   
3    255    255    255    255    255    255    255    255    255    255  ...   

   12278  12279  12280  12281  12282  12283  12284  12285  12286  12287  
0    211    210    208    209    209    207    208    208    206    207  
1    244    248    246    249    247    245    255    247    245    255  
2    177    174    173    179    176    173    180    177    174    181  
3    255    255    255    255    255    255    255    255    255    255  

[4 rows x 12288 columns]

In [193]:
df=df/255.0

In [194]:
df

0         1         2         3         4         5         6      \
0  0.901961  0.894118  0.898039  0.901961  0.894118  0.898039  0.898039   
1  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627   
2  0.741176  0.741176  0.749020  0.741176  0.741176  0.749020  0.741176   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      7         8         9      ...     12278     12279     12280     12281  \
0  0.890196  0.901961  0.898039  ...  0.827451  0.823529  0.815686  0.819608   
1  0.968627  0.968627  0.968627  ...  0.956863  0.972549  0.964706  0.976471   
2  0.741176  0.749020  0.741176  ...  0.694118  0.682353  0.678431  0.701961   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   

      12282     12283     12284     12285     12286     12287  
0  0.819608  0.811765  0.815686  0.815686  0.807843  0.811765  
1  0.968627  0.960784  1.000000  0.968627  0.960784  1.000000  
2  0.690196  0.678431  0.705882  0.694118  0.682353  0.709804  
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  

[4 rows x 12288 columns]

In [195]:
from sklearn.decomposition import PCA

In [196]:
pca = PCA(n_components = 2)

In [197]:
pca_df = pca.fit_transform(df)

In [198]:
df = pd.DataFrame(pca_df,columns=['f1','f2'])

In [199]:
df

f1         f2
0  -6.613401  -8.059849
1 -15.586459 -14.267295
2 -10.711291  23.164491
3  32.911151  -0.837346

In [200]:
df

f1         f2
0  -6.613401  -8.059849
1 -15.586459 -14.267295
2 -10.711291  23.164491
3  32.911151  -0.837346

In [201]:
from scipy.spatial.distance import cosine

In [202]:

df['result'] = df.apply(lambda row: cosine(row,df.iloc[-1]), axis=1)

In [203]:
df

f1         f2    result
0  -6.613401  -8.059849  1.614460
1 -15.586459 -14.267295  1.720220
2 -10.711291  23.164491  1.442654
3  32.911151  -0.837346  0.000000

In [204]:
df['id'] = ['img_1','img_2','img_3','img_4']

In [205]:
df

f1         f2    result     id
0  -6.613401  -8.059849  1.614460  img_1
1 -15.586459 -14.267295  1.720220  img_2
2 -10.711291  23.164491  1.442654  img_3
3  32.911151  -0.837346  0.000000  img_4

In [209]:
with open('pixels.pkl','wb') as f:
    pickle.dump(p,f)

In [210]:
with open('pixels.pkl','rb') as f:
    newlist = pickle.load(f)

In [211]:
newlist

[array([230, 228, 229, ..., 208, 206, 207], dtype=uint8),
 array([247, 247, 247, ..., 247, 245, 255], dtype=uint8),
 array([189, 189, 191, ..., 177, 174, 181], dtype=uint8)]