In [39]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
from PIL import Image
import pickle 

In [40]:
def Add_Image(path):
    df = pd.read_csv('data.csv')
    img=Image.open(path)
    new_img=img.resize((64,64),Image.ANTIALIAS)
    new_img.save('image_test.jpg')
    k=cv2.imread(f'image_test.jpg')
    k=k.reshape(-1,12288)
    print(k)
    
    return k

In [41]:
with open('pixels.pkl','rb') as f:
    p = pickle.load(f)

In [42]:
p

[array([230, 228, 229, ..., 208, 206, 207], dtype=uint8),
 array([247, 247, 247, ..., 247, 245, 255], dtype=uint8),
 array([189, 189, 191, ..., 177, 174, 181], dtype=uint8)]

In [43]:
k=Add_Image('img_4.jpg')

[[255 255 255 ... 255 255 255]]


In [44]:
p.append(k[0])

In [45]:
p

[array([230, 228, 229, ..., 208, 206, 207], dtype=uint8),
 array([247, 247, 247, ..., 247, 245, 255], dtype=uint8),
 array([189, 189, 191, ..., 177, 174, 181], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8)]

In [46]:
k=Add_Image('target.jpg')

[[214 225 229 ... 230 239 252]]


In [47]:
p.append(k[0])

In [92]:
df=pd.DataFrame(p)

In [93]:
df

0      1      2      3      4      5      6      7      8      9      ...  \
0    230    228    229    230    228    229    229    227    230    229  ...   
1    247    247    247    247    247    247    247    247    247    247  ...   
2    189    189    191    189    189    191    189    189    191    189  ...   
3    255    255    255    255    255    255    255    255    255    255  ...   
4    214    225    229    214    225    229    215    226    230    215  ...   

   12278  12279  12280  12281  12282  12283  12284  12285  12286  12287  
0    211    210    208    209    209    207    208    208    206    207  
1    244    248    246    249    247    245    255    247    245    255  
2    177    174    173    179    176    173    180    177    174    181  
3    255    255    255    255    255    255    255    255    255    255  
4    252    222    239    252    228    240    252    230    239    252  

[5 rows x 12288 columns]

In [76]:
df/=255

In [77]:
df

0         1         2         3         4         5         6      \
0  0.901961  0.894118  0.898039  0.901961  0.894118  0.898039  0.898039   
1  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627   
2  0.741176  0.741176  0.749020  0.741176  0.741176  0.749020  0.741176   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4  0.839216  0.882353  0.898039  0.839216  0.882353  0.898039  0.843137   

      7         8         9      ...     12278     12279     12280     12281  \
0  0.890196  0.901961  0.898039  ...  0.827451  0.823529  0.815686  0.819608   
1  0.968627  0.968627  0.968627  ...  0.956863  0.972549  0.964706  0.976471   
2  0.741176  0.749020  0.741176  ...  0.694118  0.682353  0.678431  0.701961   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
4  0.886275  0.901961  0.843137  ...  0.988235  0.870588  0.937255  0.988235   

      12282     12283     12284     12285     12286     12287  
0  0.819608  0.811765  0.815686  0.815686  0.807843  0.811765  
1  0.968627  0.960784  1.000000  0.968627  0.960784  1.000000  
2  0.690196  0.678431  0.705882  0.694118  0.682353  0.709804  
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
4  0.894118  0.941176  0.988235  0.901961  0.937255  0.988235  

[5 rows x 12288 columns]

In [52]:
from sklearn.preprocessing import StandardScaler

In [55]:
df_mod = StandardScaler().fit_transform(df)

In [56]:
df_1 = pd.DataFrame(df_mod)

In [57]:
df_1

0         1         2         3         4         5        6      \
0  0.126638 -0.034970 -0.054357  0.126638 -0.034970 -0.054357  0.08488   
1  0.844250  0.795557  0.760999  0.844250  0.795557  0.760999  0.84880   
2 -1.604075 -1.739734 -1.775665 -1.604075 -1.739734 -1.775665 -1.61272   
3  1.181950  1.145252  1.123380  1.181950  1.145252  1.123380  1.18832   
4 -0.548763 -0.166105 -0.054357 -0.548763 -0.166105 -0.054357 -0.50928   

      7         8        9      ...     12278     12279     12280     12281  \
0 -0.078742 -0.027199  0.08488  ... -0.563087 -0.406520 -0.538399 -0.659648   
1  0.796165  0.743430  0.84880  ...  0.542976  0.902612  0.724512  0.672975   
2 -1.741065 -1.795111 -1.61272  ... -1.702667 -1.646749 -1.701607 -1.659115   
3  1.146128  1.106078  1.18832  ...  0.911664  1.143767  1.023623  0.872868   
4 -0.122487 -0.027199 -0.50928  ...  0.811113  0.006890  0.491871  0.772921   

      12282     12283     12284     12285     12286     12287  
0 -0.493129 -0.563668 -0.716191 -0.545209 -0.596604 -0.753067  
1  0.845364  0.696296  0.813853  0.835515  0.710562  0.818551  
2 -1.655504 -1.691005 -1.627706 -1.642707 -1.669150 -1.604360  
3  1.127152  1.027866  0.813853  1.118740  1.045732  0.818551  
4  0.176117  0.530511  0.716191  0.233661  0.509459  0.720325  

[5 rows x 12288 columns]

In [83]:
from scipy.spatial.distance import cosine

In [100]:
#Without PCA
df['result'] = df.apply(lambda row: cosine(row,df.iloc[-1]), axis=1)
print(df)

     0    1    2    3    4    5    6    7    8    9  ...  12279  12280  12281  \
0  230  228  229  230  228  229  229  227  230  229  ...    210    208    209   
1  247  247  247  247  247  247  247  247  247  247  ...    248    246    249   
2  189  189  191  189  189  191  189  189  191  189  ...    174    173    179   
3  255  255  255  255  255  255  255  255  255  255  ...    255    255    255   
4  214  225  229  214  225  229  215  226  230  215  ...    222    239    252   

   12282  12283  12284  12285  12286  12287    result  
0    209    207    208    208    206    207  0.083722  
1    247    245    255    247    245    255  0.107662  
2    176    173    180    177    174    181  0.129023  
3    255    255    255    255    255    255  0.074088  
4    228    240    252    230    239    252  0.000000  

[5 rows x 12289 columns]


In [ ]:
#With PCA

In [94]:
from sklearn.decomposition import PCA

In [95]:
pca = PCA(n_components = 2)

In [96]:
pca_df = pca.fit_transform(df)

In [97]:
df_2 = pd.DataFrame(pca_df,columns=['f1','f2'])

In [103]:
#Without PCA
df_2['result'] = df_2.apply(lambda row: cosine(row,df_2.iloc[0]), axis=1)
print(df_2)

            f1           f2    result
0 -2488.590509 -1736.775058  0.000000
1 -4609.944720 -3534.567660  0.001004
2 -4093.931551  5689.047856  0.985542
3  6979.340488  1602.961033  1.927340
4  4213.126291 -2020.666171  1.491908


In [101]:
df.head()

0    1    2    3    4    5    6    7    8    9  ...  12279  12280  12281  \
0  230  228  229  230  228  229  229  227  230  229  ...    210    208    209   
1  247  247  247  247  247  247  247  247  247  247  ...    248    246    249   
2  189  189  191  189  189  191  189  189  191  189  ...    174    173    179   
3  255  255  255  255  255  255  255  255  255  255  ...    255    255    255   
4  214  225  229  214  225  229  215  226  230  215  ...    222    239    252   

   12282  12283  12284  12285  12286  12287    result  
0    209    207    208    208    206    207  0.083722  
1    247    245    255    247    245    255  0.107662  
2    176    173    180    177    174    181  0.129023  
3    255    255    255    255    255    255  0.074088  
4    228    240    252    230    239    252  0.000000  

[5 rows x 12289 columns]

In [108]:
#Without PCA
df['result'] = df.apply(lambda row: cosine(row,df.iloc[-1]), axis=1)
print(df)

     0    1    2    3    4    5    6    7    8    9  ...  12279  12280  12281  \
0  230  228  229  230  228  229  229  227  230  229  ...    210    208    209   
1  247  247  247  247  247  247  247  247  247  247  ...    248    246    249   
2  189  189  191  189  189  191  189  189  191  189  ...    174    173    179   
3  255  255  255  255  255  255  255  255  255  255  ...    255    255    255   
4  214  225  229  214  225  229  215  226  230  215  ...    222    239    252   

   12282  12283  12284  12285  12286  12287    result  
0    209    207    208    208    206    207  0.083722  
1    247    245    255    247    245    255  0.107662  
2    176    173    180    177    174    181  0.129023  
3    255    255    255    255    255    255  0.074088  
4    228    240    252    230    239    252  0.000000  

[5 rows x 12289 columns]


In [111]:
result  = np.array(df['result'])

In [113]:
vals = result.argsort()

In [114]:
vals

array([4, 3, 0, 1, 2], dtype=int64)

In [116]:
df['id']=['img_1','img_2','img_3','img_4','img_target']

In [118]:
l=[]
for x in vals[1:]:
    l.append(df.iloc[x]['id'])
    

In [119]:
l

['img_4', 'img_1', 'img_2', 'img_3']

In [123]:
def Get_Results():
    pass

In [124]:
k=Add_Image('target_2.jpg')

[[255 255 255 ... 253 253 255]]


In [125]:
p.append(k[0])

In [127]:
df=pd.DataFrame(p)

In [128]:
df/=255
df

0         1         2         3         4         5         6      \
0  0.901961  0.894118  0.898039  0.901961  0.894118  0.898039  0.898039   
1  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627   
2  0.741176  0.741176  0.749020  0.741176  0.741176  0.749020  0.741176   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4  0.839216  0.882353  0.898039  0.839216  0.882353  0.898039  0.843137   
5  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      7         8         9      ...     12278     12279     12280     12281  \
0  0.890196  0.901961  0.898039  ...  0.827451  0.823529  0.815686  0.819608   
1  0.968627  0.968627  0.968627  ...  0.956863  0.972549  0.964706  0.976471   
2  0.741176  0.749020  0.741176  ...  0.694118  0.682353  0.678431  0.701961   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
4  0.886275  0.901961  0.843137  ...  0.988235  0.870588  0.937255  0.988235   
5  1.000000  1.000000  1.000000  ...  1.000000  0.992157  0.980392  1.000000   

      12282     12283     12284     12285     12286     12287  
0  0.819608  0.811765  0.815686  0.815686  0.807843  0.811765  
1  0.968627  0.960784  1.000000  0.968627  0.960784  1.000000  
2  0.690196  0.678431  0.705882  0.694118  0.682353  0.709804  
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
4  0.894118  0.941176  0.988235  0.901961  0.937255  0.988235  
5  0.992157  0.988235  1.000000  0.992157  0.992157  1.000000  

[6 rows x 12288 columns]

In [129]:
#Without PCA
df['result'] = df.apply(lambda row: cosine(row,df.iloc[-1]), axis=1)
print(df)

          0         1         2         3         4         5         6  \
0  0.901961  0.894118  0.898039  0.901961  0.894118  0.898039  0.898039   
1  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627   
2  0.741176  0.741176  0.749020  0.741176  0.741176  0.749020  0.741176   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4  0.839216  0.882353  0.898039  0.839216  0.882353  0.898039  0.843137   
5  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

          7         8         9  ...     12279     12280     12281     12282  \
0  0.890196  0.901961  0.898039  ...  0.823529  0.815686  0.819608  0.819608   
1  0.968627  0.968627  0.968627  ...  0.972549  0.964706  0.976471  0.968627   
2  0.741176  0.749020  0.741176  ...  0.682353  0.678431  0.701961  0.690196   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
4  0.886275  0.901961  0.843137  ...  0.870588  0.937255  0.988235  0.8941

In [130]:
df['id']=['img_1_g','img_2_g','img_3_r','img_4_r','img_target_g','img_target_2_r']

In [135]:
df

0         1         2         3         4         5         6  \
0  0.901961  0.894118  0.898039  0.901961  0.894118  0.898039  0.898039   
1  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627  0.968627   
2  0.741176  0.741176  0.749020  0.741176  0.741176  0.749020  0.741176   
3  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4  0.839216  0.882353  0.898039  0.839216  0.882353  0.898039  0.843137   
5  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

          7         8         9  ...     12280     12281     12282     12283  \
0  0.890196  0.901961  0.898039  ...  0.815686  0.819608  0.819608  0.811765   
1  0.968627  0.968627  0.968627  ...  0.964706  0.976471  0.968627  0.960784   
2  0.741176  0.749020  0.741176  ...  0.678431  0.701961  0.690196  0.678431   
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
4  0.886275  0.901961  0.843137  ...  0.937255  0.988235  0.894118  0.941176   
5  1.000000  1.000000  1.000000  ...  0.980392  1.000000  0.992157  0.988235   

      12284     12285     12286     12287    result              id  
0  0.815686  0.815686  0.807843  0.811765  0.106194         img_1_g  
1  1.000000  0.968627  0.960784  1.000000  0.135665         img_2_g  
2  0.705882  0.694118  0.682353  0.709804  0.120647         img_3_r  
3  1.000000  1.000000  1.000000  1.000000  0.066048         img_4_r  
4  0.988235  0.901961  0.937255  0.988235  0.079962    img_target_g  
5  1.000000  0.992157  0.992157  1.000000  0.000000  img_target_2_r  

[6 rows x 12290 columns]

In [131]:
result  = np.array(df['result'])

In [132]:
vals = result.argsort()

In [133]:
l=[]
for x in vals[1:]:
    l.append(df.iloc[x]['id'])
    

In [134]:
l

['img_4_r', 'img_target_g', 'img_1_g', 'img_3_r', 'img_2_g']